# Generated by Django 6.0.4 on 2026-04-27 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_culte', models.CharField(choices=[('dimanche', 'Dimanche'), ('mercredi', 'Mercredi'), ('special', 'Spécial'), ('autre', 'Autre')], default='dimanche', max_length=20)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('predicateur', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_participants', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('nombre_total_membres', models.IntegerField()),
                ('nombre_membres_actifs', models.IntegerField()),
                ('nombre_membres_nouveau', models.IntegerField()),
                ('nombre_membres_sorti', models.IntegerField()),
                ('taux_participation_moyen', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Statistiques',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tribu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tribus',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('actif', 'Actif'), ('sorti', 'Sorti'), ('inactif', 'Inactif')], default='nouveau', max_length=20)),
                ('date_adhesion', models.DateField(default=django.utils.timezone.now)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eglise.departement')),
                ('tribu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eglise.tribu')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('culte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eglise.culte')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eglise.membre')),
            ],
            options={
                'ordering': ['-culte__date'],
                'unique_together': {('membre', 'culte')},
            },
        ),
    ]
