# Generated by Django 6.0.4 on 2026-04-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='membres_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eglise.departement'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='tribu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eglise.tribu'),
        ),
    ]
