# Generated by Django 6.0.4 on 2026-04-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0003_membre_photo_userprofile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culte',
            name='nombre_nouveaux',
            field=models.IntegerField(default=0),
        ),
    ]
