# Generated by Django 6.0.4 on 2026-05-04 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0004_culte_nombre_nouveaux'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(choices=[(1, 'Mois 1'), (2, 'Mois 2'), (3, 'Mois 3'), (4, 'Mois 4'), (5, 'Mois 5'), (6, 'Mois 6'), (7, 'Mois 7'), (8, 'Mois 8'), (9, 'Mois 9'), (10, 'Mois 10'), (11, 'Mois 11'), (12, 'Mois 12')])),
                ('annee', models.IntegerField()),
                ('nombre_total_membres', models.IntegerField(default=0)),
                ('nombre_membres_actifs', models.IntegerField(default=0)),
                ('nombre_membres_nouveau', models.IntegerField(default=0)),
                ('nombre_membres_inactif', models.IntegerField(default=0)),
                ('nombre_membres_sorti', models.IntegerField(default=0)),
                ('nombre_tribus', models.IntegerField(default=0)),
                ('membres_par_tribu', models.JSONField(blank=True, default=dict)),
                ('nombre_departements', models.IntegerField(default=0)),
                ('membres_par_departement', models.JSONField(blank=True, default=dict)),
                ('nombre_cultes', models.IntegerField(default=0)),
                ('nombre_total_presences', models.IntegerField(default=0)),
                ('nombre_total_absences', models.IntegerField(default=0)),
                ('taux_participation_moyen', models.FloatField(default=0.0)),
                ('cultes_par_type', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_mensuels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rapports Mensuels',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
    ]
