# Generated by Django 6.0.4 on 2026-05-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0005_rapportmensuel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rapportmensuel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rapportmensuel',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_mensuels', to='eglise.departement'),
        ),
        migrations.AddField(
            model_name='rapportmensuel',
            name='tribu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_mensuels', to='eglise.tribu'),
        ),
        migrations.AlterUniqueTogether(
            name='rapportmensuel',
            unique_together={('mois', 'annee', 'tribu', 'departement')},
        ),
    ]
