# Generated by Django 6.0.4 on 2026-05-04 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0006_alter_rapportmensuel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culte',
            name='departement',
            field=models.ForeignKey(blank=True, help_text='Département si culte local', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultes_locaux', to='eglise.departement'),
        ),
        migrations.AddField(
            model_name='culte',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('tribu', 'Tribu'), ('departement', 'Département')], default='global', help_text='Global ou local à une structure', max_length=20),
        ),
        migrations.AddField(
            model_name='culte',
            name='tribu',
            field=models.ForeignKey(blank=True, help_text='Tribu si culte local', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultes_locaux', to='eglise.tribu'),
        ),
    ]
