# Generated by Django 6.0.4 on 2026-05-04 12:53

from django.db import migrations


def set_default_scope(apps, schema_editor):
    """Initialiser tous les cultes existants avec scope='global'"""
    Culte = apps.get_model('eglise', 'Culte')
    Culte.objects.filter(scope='').update(scope='global')


class Migration(migrations.Migration):

    dependencies = [
        ('eglise', '0007_culte_departement_culte_scope_culte_tribu'),
    ]

    operations = [
        migrations.RunPython(set_default_scope),
    ]
